@echo off
cd "C:\Users\borra\OneDrive\Desktop\ML Projects\market_ml"
echo Deleting stale data files to force refresh...
del /Q data\raw\*_daily_raw.parquet
del /Q data\processed\*_features.parquet
echo Refreshing price data...
C:\Users\borra\anaconda3\python.exe src/pipeline/01_fetch_data.py
echo Rebuilding features...
C:\Users\borra\anaconda3\python.exe src/pipeline/02_features.py
echo Running Regime Agent...
C:\Users\borra\anaconda3\python.exe src/agents/regime_agent.py
echo Running Signal Generator...
C:\Users\borra\anaconda3\python.exe src/pipeline/12_signal_generator.py
pause
