@echo off
cd "C:\Users\borra\OneDrive\Desktop\ML Projects\market_ml"
echo Updating price data (incremental)...
C:\Users\borra\anaconda3\python.exe src/pipeline/01_fetch_data.py
echo Rebuilding features...
C:\Users\borra\anaconda3\python.exe src/pipeline/02_features.py
echo Running Regime Agent...
C:\Users\borra\anaconda3\python.exe src/agents/regime_agent.py
echo Running Signal Generator...
C:\Users\borra\anaconda3\python.exe src/pipeline/12_signal_generator.py
pause
